{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  labels:
    app: {{ .Values.name }}
    chart: "{{ $chart_name }}-{{ $chart_version }}"
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}